---
- name: Delete a vsphere ESXI VM
  hosts: all
  connection: local

  tasks:
    - name: Delete an ESXi VM Guest
      vsphere_guest:
        vcenter_hostname: 10.10.10.11
        validate_certs: no
        username: 'Administrator@vsphere.local'
        password: 'JpMsD41mDpF!'
        guest: ans-TWBR-VM[01:02]
        state: absent
        force: yes
